server:
  contextPath: /des
  port: 8080
spring:
  application:
    name: Prifender Data Extraction Service Mock
  jackson:
    default-property-inclusion: NON_NULL
info:
  app:
    name: Prifender
    module: ${spring.application.name}
    copyright: Copyright (c) 2018 Prifender
  java:
    version: ${java.runtime.version}
