spring:
  application:
    name: Prifender Data Extraction Service
  jackson:
    default-property-inclusion: NON_NULL
info:
  app:
    name: Prifender
    module: ${spring.application.name}
    copyright: Copyright (c) 2018 Prifender
  java:
    version: ${java.runtime.version}
des:
  home: ${des.home}
  metadata: ${des.home}/desDataSources.json
  containers : 5
scheduling:
  pendingTasksQueue: DES-Tasks-Unstructured 
  taskStatusQueue: DES-TaskStatus-Unstructured
server:
  contextPath: /des
  port: ${DES_PORT:8080}
